# Create a workflow that with python 3.8 cretate a hello worl python package
# build the package and publish package using twine upload to my github package account.
name: Template Package
on:
  workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Create package
      run: |
        mkdir hello_world_package
        printf "def hello_world():\n    print('Hello, World!')" > hello_world_package/__init__.py
        printf "[metadata]\nname = hello_world\nversion = 0.0.1" > setup.cfg
        printf "from setuptools import setup\nsetup()" > setup.py
    
    - name: Build package
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade build
        python -m build
    
    - name: Publish package
      run: |
        python -m pip install --upgrade twine
        python -m twine upload --repository-url https://nuget.pkg.github.com/${{ github.repository_owner }} --skip-existing dist/*
      env:
        TWINE_USERNAME: ${{ github.actor }}
        TWINE_PASSWORD: ${{ secrets.GH_TOKEN }}