# Create a workflow that gets IP info and OS details in a txt file 
# named info.txt, zips this file, and uploads it as an artifact.
name: Template Artifact
on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get IP and OS info
      run: |
        echo "Runner Hostname: $(hostname)" > info.txt
        echo "Public IP: $(curl -s http://ipinfo.io/ip)" >> info.txt
        echo "Operating System: $(uname -a)" >> info.txt

    - name: Zip the info.txt file
      run: |
        zip info.zip info.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: info-artifact
        path: info.zip